### ISSUE TITLE
Runtime exception caused by name auto-complete feature

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [midas-isg/ls#15]
It seems location-name "_Wales [Cymru GB-CYM]_" breaks the regex used in interactors.LocationProxyRule.listUniqueNames.

! @70jk5o414 - Internal server error, for (GET) [/ls/api/unique-location-names?limit=5&q=pittsburghwa] ->
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PatternSyntaxException: Unclosed character class near index 14
Wales +[Cymru +
              ^]]

Caused by: java.util.regex.PatternSyntaxException: Unclosed character class near index 14
Wales +[Cymru +
              ^
        at java.util.regex.Pattern.error(Pattern.java:1955) ~[na:1.8.0_92]
        at java.util.regex.Pattern.clazz(Pattern.java:2548) ~[na:1.8.0_92]
        at java.util.regex.Pattern.sequence(Pattern.java:2063) ~[na:1.8.0_92]
        at java.util.regex.Pattern.expr(Pattern.java:1996) ~[na:1.8.0_92]
        at java.util.regex.Pattern.compile(Pattern.java:1696) ~[na:1.8.0_92]
        at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[na:1.8.0_92]
        at java.util.regex.Pattern.compile(Pattern.java:1028) ~[na:1.8.0_92]
        at java.lang.String.replaceFirst(String.java:2178) ~[na:1.8.0_92]
        at interactors.LocationProxyRule.listUniqueNames(LocationProxyRule.java:254) ~[classes/:na]
        at controllers.LocationServices.listUniqueNames(LocationServices.java:374) ~[classes/:2.4.3]
        at controllers.LocationServices.findLocationNames(LocationServices.java:384) ~[classes/:2.4.3]

**Comment by Amin-Tajgardoon** [comment]
It seems removing square brackets (as well as parantheses) from original names solves the issue:

`String name = originalName.replaceAll("[\\[()\\]]", "");`

What other characters should be removed?

**Comment by TerenceSperringerJr** [comment]
Actually, I think the only place this function is called is for the search bar suggestions list.

If that's the case, we really don't need to drop any characters since front-end will just encodeURI format anything from picked from suggestions anyway. We could also probably rewrite the function to be cleaner.

So when back-end returns a list that has "Wales [Cymru GB-CYM]", front-end will just use the encodedURI version "Wales%20%5BCymru%20GB-CYM%5D". I just tested this manually with the endpoint

> GET http://localhost:9000/ls?q=Wales%20%5BCymru%20GB-CYM%5D

and it worked like a charm.

**Comment by TerenceSperringerJr** [comment]
@espinoj @Amin-Tajgardoon 
I still don't have access to the als_demo database and the username and password for ls_dev ain't the same, so I have no way of determining the optimal regex for the full dataset (ls_dev skimmed down due to frequent cache issues).

**Comment by TerenceSperringerJr** [comment]
We have found the best solution is to just use a quote for the regex when processing the following line instead:
> usedName = name.replaceFirst("\\Q" + toBeRemoved + "\\E", "");

While this has fixed the problem, we've learned that the algorithm only matches for prefixes (so typing "[Cymru GB-CYM]" will not find "Wales [Cymru GB-CYM]").

**Comment by TerenceSperringerJr** [comment]
I've modified the code so that tokens that are perfect matches (ignoring case) will now be included in results. So this means "[Cymru GB-CYM]" will return results, but unfortunately it also means that "GB-CYM" will not match but "GB-CYM]" and "[Cymru" will.

```
				matchesToken = false;
				for(int i = 0; i < tokens.length; i++) {
					if(tokens[i].equalsIgnoreCase(prefixName)) {
						matchesToken = true;
						break;
					}
				}
				
				if(usedName.toLowerCase().startsWith(prefixName) || matchesToken) {
```

For this particular issue we could remove **[]<>()/,.# + any other special characters** from the token and prefix comparison so that GB-CYM would return results (but then it becomes a question of which characters to exclude again! Chinese characters, anyone?). Thoughts?

**Comment by TerenceSperringerJr** [comment]
It was pointed out that alphabetical order is lost due to priority being misplaced with the code above, so perhaps the thing to do is register token matches in a separate list and then use elements from that array should the prefix search return results less than the results size.

```
				for(int i = 0; i < tokens.length; i++) {
					if(tokens[i].equalsIgnoreCase(prefixName)) {
						tokenMatches.add(originalName);
						break;
					}
				}
/...
after loop
.../

		numWord = limit - result.size();
		for(int i = 0; i < numWord; i++) {
			map = new HashMap<>();
			map.put("name", tokenMatches.get(i));
			result.add(map);
		}
```

**Comment by sahawut** [comment]
I think @TerenceSperringerJr  covers the front-end. However, we have to fix back-end and data, too.

@Amin-Tajgardoon could you please add escaping RegEx on the back-end and clean up data those look weird.

**Comment by TerenceSperringerJr** [comment]
@sahawut actually this was all done for the function LocationProxyRule.listUniqueNames() within the Play application

**Comment by sahawut** [comment]
I think what we want is escaping RegEx not removing out unwanted characters.

Here is a reason why. I ran the blow code which is Pattern.compile("[^\\w]+", Pattern.UNICODE_CHARACTER_CLASS) and it's behavior might not what we want.

public class Exp {
    public static void main(String[] args) {
        String prefixName = "Français";
        Pattern nonUnicodePattern = Pattern.compile("[^\\w]+", Pattern.UNICODE_CHARACTER_CLASS);
        String cleanedInputString = prefixName.replaceAll(nonUnicodePattern.toString(), "");
        System.out.print(cleanedInputString);
    }
}

Output is "Franais" 
note that ç is removed.

**Comment by TerenceSperringerJr** [comment]
@sahawut I pointed out the problem with escaping regex earlier:

> I've modified the code so that tokens that are perfect matches (ignoring case) will now be included in results. So this means "[Cymru GB-CYM]" will return results, but unfortunately it also means that "GB-CYM" will not match yet "GB-CYM]" and "[Cymru" will (since tokens are space delimited).

We need to be able to handle for the case where the user types "[Cymru" or "Cymru" and the results return "Wales [Cymru GB-CYM]".

However, you were right about the regex not working. I think it's because the toString() call used the original regex and did not account for the UNICODE_CHARACTER_CLASS flag. I will try to fix use the compiled pattern instead if I can.

**Comment by Amin-Tajgardoon** [comment]
Search for "Wales [Cymru GB-CYM]" does not break the api anymore.
