### ISSUE TITLE
order of search results in front-end search-bar looks incorrect

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [midas-isg/ls#33]
try "United States of America (the)"
It is expected that "United States of America (the)" be the first result, but it is not.

**Comment by TerenceSperringerJr** [comment]
The problem is that the rankings for the queries made are independent of each other.
The first search is "United States of America (the)"
Then it's "United", then "States", then "of", then "America", and finally "(the)".

One solution is to put more weight on the full search and less on the individual terms, however it is probably best if the back-end broke the terms down and determined rankings rather than the front-end (which really should be doing one query for the full input only).

The reason the current break-down search is in effect is because people were upset that they couldn't find "pittsburgh pa". It was a quick solution for front-end to combine multiple queries, but it also required rankings to be determined by front-end.

**Comment by TerenceSperringerJr** [comment]
ls/api/locations/find-by-term?_v=2 addresses this

**Comment by Amin-Tajgardoon** [comment]
Now a new ranking is used by backend based on # unique matches, # unique terms in location name/code,  location area, and name/code alphabetical order #76
