### ISSUE TITLE
UI search by name

### ISSUE THREAD

**Issue by Amin-Tajgardoon** [midas-isg/ls#93]
To improve the response time, add "bbox" and "repPoint" to "excludedFeatureFields".

**Comment by TerenceSperringerJr** [comment]
I originally left those in because I was toying with the idea of showing locations based on rep point (honing in on said locations using the bounding box). Geometries were way too massive and varied to pull up for general searches but bounding boxes and rep points were consistently three lat/long coordinates. The response time will be improved *slightly* for larger responses but the difference would be negligible for responses with fewer results.

**Comment by TerenceSperringerJr** [comment]
**TODO: Use `AND` when user selects exact-term box suggestions**
